apiVersion: v1
kind: Pod
metadata:
  annotations:
    ad.datadoghq.com/log-to-file.logs: '[{"type":"file", "source": "log-to-file", "service": "log-test", "path": "/logs/test.log"}]'
  name: log-to-file
spec:
  restartPolicy: Never
  containers:
  - name: log-to-file
    image: alpine:latest
    command:
    - "sh"
    - "-c"
    - "x=1; while true; do a=\"${a} `printf \"$x Hello, Logging to file!\"`\"; echo \"$a\" >> /logs/test.log; sleep 10; a=\"\"; x=$((x+1)); done"
    volumeMounts:
    - mountPath: /logs
      name: log-dir
  volumes:
  - name: log-dir
    hostPath:
      path: /logs/